// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABPmFA2LEN-H-30GpT995jzLSb_bodbsc',
    appId: '1:79447508615:web:73715dd6136df13a8e5a22',
    messagingSenderId: '79447508615',
    projectId: 'robokids-66c04',
    authDomain: 'robokids-66c04.firebaseapp.com',
    storageBucket: 'robokids-66c04.firebasestorage.app',
    measurementId: 'G-789FWD46S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHOM3cKHyYFp6-o-1rl5PWQGpnYNujSI',
    appId: '1:79447508615:android:7bea69ecea463af98e5a22',
    messagingSenderId: '79447508615',
    projectId: 'robokids-66c04',
    storageBucket: 'robokids-66c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzxEnbicu_a69YI7m4hlRMtrvqR21dpU',
    appId: '1:79447508615:ios:4c202f623f76d1028e5a22',
    messagingSenderId: '79447508615',
    projectId: 'robokids-66c04',
    storageBucket: 'robokids-66c04.firebasestorage.app',
    iosBundleId: 'com.example.robokid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzxEnbicu_a69YI7m4hlRMtrvqR21dpU',
    appId: '1:79447508615:ios:4c202f623f76d1028e5a22',
    messagingSenderId: '79447508615',
    projectId: 'robokids-66c04',
    storageBucket: 'robokids-66c04.firebasestorage.app',
    iosBundleId: 'com.example.robokid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABPmFA2LEN-H-30GpT995jzLSb_bodbsc',
    appId: '1:79447508615:web:8f17d3a7de3c0eb98e5a22',
    messagingSenderId: '79447508615',
    projectId: 'robokids-66c04',
    authDomain: 'robokids-66c04.firebaseapp.com',
    storageBucket: 'robokids-66c04.firebasestorage.app',
    measurementId: 'G-3S2TWC5S2M',
  );
}
